import React, { useEffect, useState } from 'react';
import { OutboxList } from '../components/alerts/OutboxList';
import { AlertItem } from '../types';
import { api } from '../services/api';

export const AlertsPage: React.FC = () => {
  const [alerts, setAlerts] = useState<AlertItem[]>([]);

  const loadAlerts = () => {
    api.getAlerts(undefined, 100).then(setAlerts).catch(console.error);
  };

  useEffect(() => {
    loadAlerts();
    const interval = setInterval(loadAlerts, 5000);
    return () => clearInterval(interval);
  }, []);

  const handleClear = () => {
    api.clearAlerts().then(() => setAlerts([])).catch(console.error);
  };

  return (
    <div className="space-y-6 pb-12">
      
      <div className="border-b border-survey-border dark:border-night-border pb-3">
        <span className="font-mono text-xs text-survey-teal dark:text-night-teal uppercase tracking-wider block">DISASTER RESPONSE & TELEGRAM BOT LOGS</span>
        <h1 className="font-serif text-2xl font-bold text-survey-ink dark:text-night-text">Alert Outbox & Evacuation Routes</h1>
        <p className="font-sans text-xs text-survey-slate dark:text-night-slate">Every alert generated by the hysteresis engine is recorded here with English/Hindi previews and OpenStreetMap evacuation links.</p>
      </div>

      <OutboxList alerts={alerts} onClear={handleClear} />

    </div>
  );
};
