import React, { useEffect, useState } from 'react';
import { OutboxList } from '../components/alerts/OutboxList';
import { AlertItem } from '../types';
import { api } from '../services/api';

export const AlertsPage: React.FC = () => {
  const [alerts, setAlerts] = useState<AlertItem[]>([]);
  const [demoStation, setDemoStation] = useState<string>('KL-PER-01');
  const [demoRisk, setDemoRisk] = useState<string>('Orange');
  const [demoLang, setDemoLang] = useState<string>('hi');
  const [isSubmittingDemo, setIsSubmittingDemo] = useState<boolean>(false);

  const loadAlerts = () => {
    api.getAlerts(undefined, 100).then(setAlerts).catch(console.error);
  };

  useEffect(() => {
    loadAlerts();
    const interval = setInterval(loadAlerts, 5000);
    return () => clearInterval(interval);
  }, []);

  const handleClear = () => {
    api.clearAlerts().then(() => setAlerts([])).catch(console.error);
  };

  const handleTriggerDemo = async () => {
    setIsSubmittingDemo(true);
    try {
      await api.postDemoAlert(demoStation, demoRisk, demoLang);
      loadAlerts();
    } catch (err) {
      console.error('Failed to trigger demo alert:', err);
    } finally {
      setIsSubmittingDemo(false);
    }
  };

  return (
    <div className="space-y-6 pb-12">
      
      {/* Header Bar */}
      <div className="border-b border-survey-border dark:border-night-border pb-3">
        <span className="font-mono text-xs text-survey-teal dark:text-night-teal uppercase tracking-wider block">DISASTER RESPONSE & TELEGRAM BOT LOGS</span>
        <h1 className="font-serif text-2xl font-bold text-survey-ink dark:text-night-text">Alert Outbox & Evacuation Routes</h1>
        <p className="font-sans text-xs text-survey-slate dark:text-night-slate">Every alert generated by the hysteresis engine is recorded here with English, Hindi, Malayalam, and Assamese previews (native-speaker review required) and OpenStreetMap evacuation links.</p>
      </div>

      {/* DEMO ALERT Trigger Panel */}
      <div className="rounded border border-amber-300 dark:border-amber-800/60 bg-amber-50/60 dark:bg-amber-950/20 p-4 shadow-xs space-y-3">
        <div className="flex items-center justify-between">
          <span className="font-mono text-xs font-bold text-amber-800 dark:text-amber-300 uppercase tracking-wider">
            ⚡ DEMO ALERT GENERATOR (MULTILINGUAL PREVIEW)
          </span>
          <span className="font-mono text-[10px] text-amber-700 dark:text-amber-400 bg-amber-200/50 dark:bg-amber-900/50 px-2 py-0.5 rounded">
            DEMO MODE • MARKED [DEMO ALERT] IN OUTBOX
          </span>
        </div>

        <div className="flex flex-wrap items-center gap-3">
          <div>
            <label className="block font-mono text-[10px] uppercase text-survey-slate dark:text-night-slate mb-1">Station</label>
            <select
              value={demoStation}
              onChange={(e) => setDemoStation(e.target.value)}
              className="px-2.5 py-1 text-xs font-mono rounded border border-survey-border dark:border-night-border bg-survey-paper dark:bg-night-bg text-survey-ink dark:text-night-text"
            >
              <option value="KL-PER-01">KL-PER-01 (Neeleswaram)</option>
              <option value="KL-PER-02">KL-PER-02 (Aluva)</option>
              <option value="KL-PAM-01">KL-PAM-01 (Chengannur)</option>
              <option value="AS-BRA-01">AS-BRA-01 (Guwahati)</option>
              <option value="AS-BRA-02">AS-BRA-02 (Dibrugarh)</option>
            </select>
          </div>

          <div>
            <label className="block font-mono text-[10px] uppercase text-survey-slate dark:text-night-slate mb-1">Risk Class</label>
            <select
              value={demoRisk}
              onChange={(e) => setDemoRisk(e.target.value)}
              className="px-2.5 py-1 text-xs font-mono rounded border border-survey-border dark:border-night-border bg-survey-paper dark:bg-night-bg text-survey-ink dark:text-night-text"
            >
              <option value="Orange">Orange Warning</option>
              <option value="Red">Red Severe</option>
            </select>
          </div>

          <div>
            <label className="block font-mono text-[10px] uppercase text-survey-slate dark:text-night-slate mb-1">Target Language</label>
            <select
              value={demoLang}
              onChange={(e) => setDemoLang(e.target.value)}
              className="px-2.5 py-1 text-xs font-mono rounded border border-survey-border dark:border-night-border bg-survey-paper dark:bg-night-bg text-survey-ink dark:text-night-text"
            >
              <option value="hi">Hindi (हिंदी)</option>
              <option value="ml">Malayalam (മലയാളം)</option>
              <option value="as">Assamese (অসমীয়া)</option>
              <option value="en">English</option>
            </select>
          </div>

          <div className="pt-4">
            <button
              onClick={handleTriggerDemo}
              disabled={isSubmittingDemo}
              className="px-4 py-1.5 rounded font-mono text-xs font-bold text-white bg-amber-600 hover:bg-amber-700 transition-colors cursor-pointer shadow-xs disabled:opacity-50"
            >
              {isSubmittingDemo ? 'Generating...' : 'Trigger DEMO Alert'}
            </button>
          </div>
        </div>
      </div>

      <OutboxList alerts={alerts} onClear={handleClear} />

    </div>
  );
};
